
use serde::{Serialize, Deserialize};
use super::*;
#[derive(Debug, Serialize, Deserialize)]
pub enum AssetTransactionCategoryType {
    #[serde(rename = "ATMFee")]
    AtmFee,
    Advertising,
    AirTravel,
    AlcoholBars,
    Allowance,
    Amusement,
    Arts,
    AutoTransport,
    AutoInsurance,
    AutoPayment,
    BabySupplies,
    BabysitterDaycare,
    BankFee,
    BillsUtilities,
    Bonus,
    BooksSupplies,
    #[serde(rename = "Business Services")]
    BusinessServices,
    Buy,
    #[serde(rename = "CashATM")]
    CashAtm,
    Charity,
    Check,
    ChildSupport,
    Clothing,
    CoffeeShops,
    CreditCardPayment,
    Dentist,
    Doctor,
    Education,
    ElectronicsSoftware,
    Entertainment,
    Eyecare,
    FastFood,
    FederalTax,
    FeesCharges,
    FinanceCharge,
    Financial,
    FinancialAdvisor,
    FoodDining,
    Furnishings,
    GasFuel,
    GiftsDonations,
    Groceries,
    Gym,
    Hair,
    HealthFitness,
    HealthInsurance,
    Hobbies,
    Home,
    HomeImprovement,
    HomeInsurance,
    HomePhone,
    HomeServices,
    HomeSupplies,
    Hotel,
    Income,
    InterestIncome,
    Internet,
    Investments,
    Kids,
    KidsActivities,
    LateFee,
    Laundry,
    LawnGarden,
    Legal,
    LifeInsurance,
    LoanInsurance,
    LoanPayment,
    Loans,
    MobilePhone,
    MortgageRent,
    #[serde(rename = "MoviesDVDs")]
    MoviesDvDs,
    Music,
    NewspapersMagazines,
    OfficeSupplies,
    Parking,
    Paycheck,
    PersonalCare,
    PetFoodSupplies,
    PetGrooming,
    Pets,
    Pharmacy,
    Printing,
    #[serde(rename = "Property Tax")]
    PropertyTax,
    #[serde(rename = "Public Transportation")]
    PublicTransportation,
    Reimbursement,
    RentalCarTaxi,
    Restaurants,
    SalesTax,
    ServiceParts,
    ServiceFee,
    Shipping,
    Shopping,
    SpaMassage,
    SportingGoods,
    Sports,
    StateTax,
    #[serde(rename = "Student Loan")]
    StudentLoan,
    Taxes,
    Television,
    Toys,
    Transfer,
    Travel,
    Tuition,
    Uncategorized,
    Utilities,
    Vacation,
    Veterinary,
}